### ISSUE TITLE
Consider LUA sigil turning script into chunk

### ISSUE THREAD

**Issue by Papipo** [tv-labs/lua#35]
I think that given that chunks are portable and don't need a state, it might be interesting to use luerl to turn ~LUA usages into Lua chunks. After all, it's inevitable that they will be loaded at some point, so why not have them converted to chunks already?

**Comment by davydog187** [comment]
@Papipo i was planning on supporting this via a sigil modifier, e.g.

```elixir
~LUA"foo()"c
```

What do you think?

**Comment by Papipo** [comment]
That's actually perfect 👌🏽

**Comment by davydog187** [comment]
Well, the reason why I didn't do this to start is that the sigil would need to return a tuple of the chunk and the Lua state, similar to Luerl.do

Given that the shape of the return value is much different, I'm not sure it's so much of a concern

**Comment by Papipo** [comment]
Ah, true. I was thinking about [`luerl_comp.string`](https://github.com/rvirding/luerl/blob/553e375c24ee7d7fd6de79069580606689925087/src/luerl_comp.erl#L77), which doesn't need state. It might not be considered public API, though, but I think it's pretty slick to be able to carry portable chunks around.
